apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: tyfr/auth
      context: auth
      sync:
        infer:
          - 'src/**/*.ts'
    - image: tyfr/tickets
      context: tickets
      sync:
        infer:
          - 'src/**/*.ts'
    - image: tyfr/orders
      context: orders
      sync:
        infer:
          - 'src/**/*.ts'
    - image: tyfr/expiration
      context: expiration
      sync:
        infer:
          - 'src/**/*.ts'
    - image: tyfr/payments
      context: payments
      sync:
        infer:
          - 'src/**/*.ts'
    - image: tyfr/client
      context: client
      sync:
        infer:
          - '**/*.js'
        # manual:
        #   - src: "src/**/*.ts"
        #     dest: .

deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
      - ./infrastructure/k8s-dev/*
profiles:
  - name: cloudbuild
    build:
      local:
        push: false
      artifacts:
        - image: tyfr/auth
          context: auth
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: tyfr/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: '**/*.js'
                dest: .
        - image: tyfr/tickets
          context: tickets
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: tyfr/orders
          context: orders
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: tyfr/expiration
          context: expiration
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
        - image: tyfr/payments
          context: payments
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: .
# This is for Google Cloud Build
# apiVersion: skaffold/v2beta29
# kind: Config
# build:
#   tagPolicy:
#     sha256: {}
#   artifacts:
#     - image: eu.gcr.io/ticket-app-354408/auth
#       context: auth
#       sync:
#         infer:
#           - 'src/**/*.ts'
#         # manual:
#         #   - src: "src/**/*.ts"
#         #     dest: .

# deploy:
#   kubectl:
#     manifests:
#       - ./infrastructure/k8s/*
# profiles:
#   - name: cloudbuild
#     build:
#       googleCloudBuild: { projectId: ticket-app-354408 }
#       artifacts:
#         - image: eu.gcr.io/ticket-app-354408/auth
#           context: auth
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - 'src/**/*.ts'
#             # manual:
#             #   - src: "src/**/*.ts"
#             #     dest: .
