apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: eu.gcr.io/ticket-app-354408/auth
      context: auth
      sync:
        infer:
          - 'src/**/*.ts'
        # manual:
        #   - src: "src/**/*.ts"
        #     dest: .

deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: { projectId: ticket-app-354408 }
      artifacts:
        - image: eu.gcr.io/ticket-app-354408/auth
          context: auth
          docker:
            dockerfile: Dockerfile
          sync:
            infer:
              - 'src/**/*.ts'
            # manual:
            #   - src: "src/**/*.ts"
            #     dest: .
